'use strict';
Object.assign(NuageText.ru,{
 focusEnabled:'Акцент на важные панели',focusHint:'Поиск матча, карточки и боковые панели',savedWallpapers:'МОИ ФОНЫ',galleryEmpty:'Загруженные фоны появятся здесь',clearCurrent:'Убрать фон со страницы, оставив в коллекции',deleteSaved:'Удалить сохранённый фон',selectSaved:'Выбрать фон',colorEnabled:'Свой цвет FACEIT',colorHint:'Кнопки, ссылки, логотип и значки',accentColor:'Выбрать цвет FACEIT',hexColor:'Код цвета HEX',resetColor:'Оригинал',presets:'Готовые цвета',badHex:'Введи цвет в формате #A9C8FF.',removed:'Фон скрыт · все сохранённые файлы остались в коллекции',deleted:'Файл удалён из коллекции',selected:'Фон переключён',migration:'Перенос текущего фона в коллекцию…',migrationError:'Не удалось создать миниатюру старого фона. Он остаётся доступен.',gallerySize:'Сохранено',readError:'Не удалось загрузить данные. Открой расширение заново.'
});
Object.assign(NuageText.en,{
 focusEnabled:'Emphasize important panels',focusHint:'Match controls, cards and side panels',savedWallpapers:'MY WALLPAPERS',galleryEmpty:'Your imported wallpapers will appear here',clearCurrent:'Hide wallpaper, keep it in the collection',deleteSaved:'Delete saved wallpaper',selectSaved:'Use wallpaper',colorEnabled:'Custom FACEIT color',colorHint:'Buttons, links, logo and icons',accentColor:'Choose FACEIT color',hexColor:'HEX color code',resetColor:'Original',presets:'Color presets',badHex:'Enter a color such as #A9C8FF.',removed:'Wallpaper hidden · your saved files remain in the collection',deleted:'File deleted from the collection',selected:'Wallpaper switched',migration:'Adding your current wallpaper to the collection…',migrationError:'Could not create the old wallpaper thumbnail. The wallpaper is still available.',gallerySize:'Saved',readError:'Could not load data. Reopen the extension.'
});
// 3.2 — panel styles, glow, interface cleanup.
Object.assign(NuageText.ru,{
 interface:'Интерфейс',title_interface:'Только то, что нужно',interfaceIntro:'Убери лишнее с экрана FACEIT. Изменения применяются сразу.',
 panelStyle:'Стиль панелей',styleClassic:'Классика',styleClassicHint:'Тёмные подложки',styleGlass:'Стекло',styleGlassHint:'Матовое, как в iOS',styleWater:'Вода',styleWaterHint:'Прозрачные блики',
 glassBlur:'Размытие стекла',radius:'Скругление углов',radiusSite:'как на сайте',focus:'Плотность панелей',
 modeGlow:'Свечение выбранного режима',modeGlowHint:'Стандартный матч, Суперматч, Premium',ctaGlow:'Свечение «Найти матч»',ctaGlowHint:'Мягкий ореол вокруг главной кнопки',glowPulse:'Плавная пульсация',glowPulseHint:'Свечение медленно «дышит»',glowColor:'Цвет свечения',glowWhite:'Белый',glowAccent:'Цвет FACEIT',
 hideEsea:'Скрыть ESEA-лигу',hideEseaHint:'Баннер «Зарегистрируйтесь сейчас» сверху',hideMissions:'Скрыть миссии',hideMissionsHint:'Карточка «Выиграй 10 матчей» и прогресс',hideQueue:'Скрыть счётчик очереди',hideQueueHint:'«Текущие матчи · Игроки в очереди»',hideBadges:'Скрыть значки «Новое»',hideBadgesHint:'«НОВАЯ КАРТА», «НОВИНКА» и похожие',thinScroll:'Тонкие полосы прокрутки',thinScrollHint:'Полупрозрачные и незаметные'
});
Object.assign(NuageText.en,{
 interface:'Interface',title_interface:'Only what matters',interfaceIntro:'Remove clutter from FACEIT. Changes apply instantly.',
 panelStyle:'Panel style',styleClassic:'Classic',styleClassicHint:'Dark backplates',styleGlass:'Glass',styleGlassHint:'Frosted, iOS-like',styleWater:'Water',styleWaterHint:'Clear, liquid shine',
 glassBlur:'Glass blur',radius:'Corner radius',radiusSite:'site default',focus:'Panel density',
 modeGlow:'Glow on selected match type',modeGlowHint:'Standard, Super Match, Premium',ctaGlow:'«Find match» glow',ctaGlowHint:'Soft halo around the main button',glowPulse:'Gentle pulse',glowPulseHint:'The glow slowly breathes',glowColor:'Glow color',glowWhite:'White',glowAccent:'FACEIT color',
 hideEsea:'Hide ESEA league',hideEseaHint:'The «Register now» banner at the top',hideMissions:'Hide missions',hideMissionsHint:'«Win 10 matches» card and progress',hideQueue:'Hide queue counter',hideQueueHint:'«Current matches · Players in queue»',hideBadges:'Hide «New» badges',hideBadgesHint:'«NEW MAP», «NEW» and similar',thinScroll:'Thin scrollbars',thinScrollHint:'Translucent and unobtrusive'
});
// 3.3
Object.assign(NuageText.ru,{radiusSite:'авто',hideElo:'Скрыть панель Elo',hideEloHint:'Значок ранга, «Сезон», Prestige Path и Elo',clearMatchPanel:'Убрать подложку панели матча',clearMatchPanelHint:'Фон другого цвета вокруг «Тип матча» и карточек',hidePartyText:'Только значок в «Поиске группы»',hidePartyTextHint:'Убирает надпись в правом слоте группы',ctaText:'Текст кнопки «Найти матч»',ctaTextHint:'До 24 символов. Пусто — текст FACEIT. Enter — сохранить'});
Object.assign(NuageText.en,{radiusSite:'auto',hideElo:'Hide the Elo panel',hideEloHint:'Rank badge, «Season», Prestige Path and Elo',clearMatchPanel:'Remove the match panel backplate',clearMatchPanelHint:'The differently colored area around match type and cards',hidePartyText:'Icon only in «Find party»',hidePartyTextHint:'Removes the caption in the right party slot',ctaText:'«Find match» button text',ctaTextHint:'Up to 24 characters. Empty — FACEIT text. Enter to save'});
// 3.4
Object.assign(NuageText.ru,{minimalAvatar:'Минималистичная аватарка',minimalAvatarHint:'Только круглое фото: без рамки и значка Premium',hideInviteSlots:'Скрыть слоты приглашения',hideInviteSlotsHint:'Только ты и тиммейты — пустые слоты и «Поиск группы» скрыты',hideLadders:'Скрыть ладдеры',hideLaddersHint:'Блок «Ладдеры» внизу главной страницы',hideScrollbars:'Скрыть полосы прокрутки',hideScrollbarsHint:'Прокрутка колесом и тачпадом работает как раньше',hideDividers:'Убрать разделительные линии',hideDividersHint:'Тонкие полосы между блоками и в меню слева'});
Object.assign(NuageText.en,{minimalAvatar:'Minimal avatar',minimalAvatarHint:'Just the round photo: no frame, no Premium badge',hideInviteSlots:'Hide invite slots',hideInviteSlotsHint:'Only you and your teammates — empty slots and «Find party» hidden',hideLadders:'Hide ladders',hideLaddersHint:'The «Ladders» block at the bottom of the home page',hideScrollbars:'Hide scrollbars',hideScrollbarsHint:'Wheel and touchpad scrolling still work',hideDividers:'Remove divider lines',hideDividersHint:'Thin lines between blocks and in the left menu'});
// 3.7
Object.assign(NuageText.ru,{fontFamily:'Шрифт FACEIT',fontDefault:'Как у FACEIT',fontCustom:'Свой файл',fontUpload:'Загрузить шрифт…',fontRemove:'Удалить загруженный шрифт',fontLoaded:'Шрифт загружен',fontError:'Не удалось прочитать шрифт. Подходят TTF, OTF, WOFF, WOFF2 до 8 МБ.',textColorEnabled:'Свой цвет текста',textColorHint:'Белый и серый текст FACEIT; цветные показатели не меняются',textColor:'Цвет текста',presets:'Пресеты',presetsHint:'Один файл: все настройки, текущий фон (фото или видео) и шрифт. Отправь его другу — он нажмёт «Загрузить пресет».',presetExport:'Сохранить пресет',presetImport:'Загрузить пресет',presetSaved:'Пресет сохранён в «Загрузки»',presetLoaded:'Пресет применён',presetError:'Это не файл пресета XLR или он повреждён.',presetBuilding:'Собираю пресет…',presetReading:'Загружаю пресет… не закрывай окно'});
Object.assign(NuageText.en,{fontFamily:'FACEIT font',fontDefault:'FACEIT default',fontCustom:'Custom file',fontUpload:'Upload font…',fontRemove:'Remove uploaded font',fontLoaded:'Font loaded',fontError:'Could not read the font. Use TTF, OTF, WOFF or WOFF2 up to 8 MB.',textColorEnabled:'Custom text color',textColorHint:'White and grey FACEIT text; colored stats stay as they are',textColor:'Text color',presets:'Presets',presetsHint:'One file: all settings, the current wallpaper (image or video) and font. Send it to a friend — they press «Load preset».',presetExport:'Save preset',presetImport:'Load preset',presetSaved:'Preset saved to Downloads',presetLoaded:'Preset applied',presetError:'Not an XLR preset file, or it is damaged.',presetBuilding:'Building the preset…',presetReading:'Loading the preset… keep this window open'});
// 3.8
Object.assign(NuageText.ru,{pickTitle:'Свои скрытые элементы',pickHint:'Нажми кнопку и кликни по любому элементу на FACEIT, чтобы скрыть его. Зажми Ctrl, чтобы удалить сразу несколько объектов подряд без повторного открытия меню. Клик у края блока убирает только его линию.',pickStart:'Убрать элемент на странице (Ctrl — несколько)',pickNoTab:'Открой вкладку FACEIT и попробуй снова.',hiddenClear:'Вернуть всё',hiddenRestore:'Вернуть',hiddenLines:'линии',hiddenHide:'скрыт'});
Object.assign(NuageText.en,{pickTitle:'Your hidden elements',pickHint:'Click any FACEIT element to hide it. Hold Ctrl to remove multiple objects without reopening the menu. A click at a block edge removes only its line.',pickStart:'Hide element on page (Ctrl for multiple)',pickNoTab:'Open a FACEIT tab and try again.',hiddenClear:'Restore all',hiddenRestore:'Restore',hiddenLines:'lines',hiddenHide:'hidden'});
Object.assign(NuageText.ru,{aboutName:'XLR — Выбери, как должен выглядеть твой клиент, пусть ничто не ограничивает твои возможности.'});Object.assign(NuageText.en,{aboutName:'XLR — Choose how your client should look, let nothing limit your possibilities.'});
